version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  pconfig:
    build: .
    image: phpmicroservice/pconfig:master
    privileged: false
    restart: unless-stopped
    ports:
    - 9016:80
    environment:
    - PMA_ARBITRARY=1
  dev:
    build:
      context: .
      dockerfile: DockerfileDev
    image: pconfig:dev
    privileged: false
    restart: unless-stopped
    ports:
      - 9017:80
    environment:
      - DATABASE_TYPE=mysql
      - SITE_NAME=开发测试
    volumes:
      - .:/var/www/html