version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  pconfig:
    build: .
    image: pconfig:master
    privileged: false
    restart: unless-stopped
    ports:
    - 9016:80
    environment:
    - PMA_ARBITRARY=1