version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php:
    build: build
    image: spma_pconfig:master
    privileged: false
    restart: unless-stopped
    ports:
    - 80
    volumes:
    - .:/var/www/html